name: Glow Lashes
favicon: null
layout_spectrum: 0.3678043317049742
typography_spectrum: 0.0003404493909329176
title: Gallery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130013'
    - '#f2fee8'
    - '#b37953'
    - '#854635'
    - '#f1c179'
  brandStrength: 0.23668143688701093
  lightness: 0.8368736472912133
  saturation: 0.16017309366725385
  rhythmicContrast: 0.04731814097613096
purpose: []
