name: Glow Lashes
favicon: null
layout_spectrum: 0.3678043317049742
typography_spectrum: 0.0003404493909329176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.23668143688701093
  lightness: 0.8368736472912133
  saturation: 0.16017309366725385
  rhythmicContrast: 0.04731814097613096
purpose: []
